/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Despesa.DespesasController;
import controller.Estoque.EstoqueController;
import controller.Estoque.NovoItemEstoqueController;
import controller.Itens.ItensCotroller;
import controller.Vendas.DetalheVendaController;
import controller.Vendas.VendasController;
import dao.GerarTabela;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Estoque;
import model.Item;
import model.Venda;
import view.Despesas.NovaDespesa;
import view.Despesas.TotalDespesasPorItem;
import view.Estoque.NovoItemEstoque;
import view.Itens.EditarItem;
import view.Itens.NovoItem;
import view.Vendas.DetalheVenda;

import view.Vendas.NovoVenda;
import view.Vendas.TotalVendasPorItem;

/**
 *
 * @author Tiago Ventura
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private final ItensCotroller itensCotroller;
    private final EstoqueController estoqueController;
    private final VendasController vendasController;
    private final DespesasController despesasController;
    
    public TelaPrincipal() throws IOException, ClassNotFoundException, SQLException {
        initComponents();
        visisbleFalse();
        jPanelItem.setVisible(true);
        GerarTabela.main();
        
        itensCotroller = new ItensCotroller(this);
        
        estoqueController = new EstoqueController(this);
        
        vendasController = new VendasController(this);
       
        despesasController = new DespesasController(this);
    }
    
    public void visisbleFalse(){
        jPanelItem.setVisible(false);
        jPanelEstoque.setVisible(false);
        jPanelVenda.setVisible(false);
        jPanelDespesa.setVisible(false);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLateral = new javax.swing.JPanel();
        jButtonVendas = new javax.swing.JButton();
        jButtonDesoesas = new javax.swing.JButton();
        jButtonItens = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jPanelItem = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Itens_Descricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Itens_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_Itens_Buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelOpcoes = new javax.swing.JPanel();
        jPanelListaItens = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Itens_TabelaItens = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton_Itens_Editar = new javax.swing.JButton();
        jButton_Itens_Apagar = new javax.swing.JButton();
        jButton_Itens_NovoItem = new javax.swing.JButton();
        jPanelEstoque = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Estoque_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Estoque_codigp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_Estoque_buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanelOpcoes1 = new javax.swing.JPanel();
        jPanelListaItens1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Estoque_tabela = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton_Estoque_editar = new javax.swing.JButton();
        jButton_Estoque_apagar = new javax.swing.JButton();
        jButton_Estoque_novoItem = new javax.swing.JButton();
        jPanelVenda = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Vendas_data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_Venda_buscar_mes = new javax.swing.JButton();
        jButton_Vendas_buscarData = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_Vendas_meses = new javax.swing.JComboBox();
        jComboBox_Vendas_ano = new javax.swing.JComboBox();
        jPanelOpcoes2 = new javax.swing.JPanel();
        jButton_Vendas_totalItensVendidos = new javax.swing.JButton();
        jPanelListaItens2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Vendas_tabela = new javax.swing.JTable();
        jTextField_Vendas_total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton_Vendas_NovaVenda = new javax.swing.JButton();
        jButton_Vendas_Detalhe = new javax.swing.JButton();
        jLabel_Vendas_vendasDe = new javax.swing.JLabel();
        jPanelDespesa = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton_Despesas_buscar_mesAno = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jComboBox_Despesas_meses = new javax.swing.JComboBox();
        jComboBox_Despesas_anos = new javax.swing.JComboBox();
        jPanelOpcoes3 = new javax.swing.JPanel();
        jButton_Despesas_totalDespesasPorItem = new javax.swing.JButton();
        jPanelListaItens3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Despesas_tabela = new javax.swing.JTable();
        jTextField_Despesas_total = new javax.swing.JTextField();
        jLabel_Despesas_totalDe = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton_Despesas_novaDespesa = new javax.swing.JButton();
        jLabel_Despesas_despesasDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(61, 195, 195));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(23, 35, 51));
        MenuLateral.setForeground(new java.awt.Color(23, 35, 51));
        MenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVendas.setBackground(javax.swing.UIManager.getDefaults().getColor("windowBorder"));
        jButtonVendas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVendas.setText("Vendas");
        jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendasActionPerformed(evt);
            }
        });
        MenuLateral.add(jButtonVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 40));

        jButtonDesoesas.setBackground(javax.swing.UIManager.getDefaults().getColor("windowBorder"));
        jButtonDesoesas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesoesas.setText("Despesas");
        jButtonDesoesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesoesasActionPerformed(evt);
            }
        });
        MenuLateral.add(jButtonDesoesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 40));

        jButtonItens.setBackground(javax.swing.UIManager.getDefaults().getColor("windowBorder"));
        jButtonItens.setForeground(new java.awt.Color(255, 255, 255));
        jButtonItens.setText("Itens");
        jButtonItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItensActionPerformed(evt);
            }
        });
        MenuLateral.add(jButtonItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 210, 40));

        jButton9.setBackground(new java.awt.Color(23, 35, 51));
        jButton9.setForeground(new java.awt.Color(23, 35, 51));
        jButton9.setText("jButton1");
        MenuLateral.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 180, 40));

        getContentPane().add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 670));

        jPanelContent.setLayout(new javax.swing.OverlayLayout(jPanelContent));

        jPanelItem.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        jTextField_Itens_Descricao.setBackground(new java.awt.Color(123, 156, 225));
        jTextField_Itens_Descricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Itens_Descricao.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição");

        jTextField_Itens_Codigo.setBackground(new java.awt.Color(123, 156, 225));
        jTextField_Itens_Codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Itens_Codigo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código");

        jButton_Itens_Buscar.setBackground(new java.awt.Color(71, 120, 197));
        jButton_Itens_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Itens_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8_Search_18px.png"))); // NOI18N
        jButton_Itens_Buscar.setText("Buscar");
        jButton_Itens_Buscar.setBorder(null);
        jButton_Itens_Buscar.setBorderPainted(false);
        jButton_Itens_Buscar.setFocusable(false);
        jButton_Itens_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Itens_BuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Itens");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Itens_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Itens_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton_Itens_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Itens_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField_Itens_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButton_Itens_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTable_Itens_TabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "", null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descrição", "Código", "Categoria", "Preço Unit.", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Itens_TabelaItens.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable_Itens_TabelaItens);

        javax.swing.GroupLayout jPanelListaItensLayout = new javax.swing.GroupLayout(jPanelListaItens);
        jPanelListaItens.setLayout(jPanelListaItensLayout);
        jPanelListaItensLayout.setHorizontalGroup(
            jPanelListaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
        );
        jPanelListaItensLayout.setVerticalGroup(
            jPanelListaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton_Itens_Editar.setText("Editar");
        jButton_Itens_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Itens_EditarActionPerformed(evt);
            }
        });

        jButton_Itens_Apagar.setText("Apagar");

        jButton_Itens_NovoItem.setText("Novo Item");
        jButton_Itens_NovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Itens_NovoItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jButton_Itens_NovoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Itens_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Itens_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Itens_NovoItem)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Itens_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Itens_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelItemLayout = new javax.swing.GroupLayout(jPanelItem);
        jPanelItem.setLayout(jPanelItemLayout);
        jPanelItemLayout.setHorizontalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListaItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelItemLayout.setVerticalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelItemLayout.createSequentialGroup()
                        .addComponent(jPanelListaItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        jPanelContent.add(jPanelItem);

        jPanelEstoque.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(71, 120, 197));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });

        jTextField_Estoque_descricao.setBackground(new java.awt.Color(123, 156, 225));
        jTextField_Estoque_descricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Estoque_descricao.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição");

        jTextField_Estoque_codigp.setBackground(new java.awt.Color(123, 156, 225));
        jTextField_Estoque_codigp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Estoque_codigp.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código");

        jButton_Estoque_buscar.setBackground(new java.awt.Color(71, 120, 197));
        jButton_Estoque_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Estoque_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8_Search_18px.png"))); // NOI18N
        jButton_Estoque_buscar.setText("Buscar");
        jButton_Estoque_buscar.setBorder(null);
        jButton_Estoque_buscar.setBorderPainted(false);
        jButton_Estoque_buscar.setFocusable(false);
        jButton_Estoque_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Estoque_buscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estoque");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Estoque_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Estoque_codigp, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_Estoque_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addGap(34, 34, 34))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Estoque_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField_Estoque_codigp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jButton_Estoque_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOpcoes1Layout = new javax.swing.GroupLayout(jPanelOpcoes1);
        jPanelOpcoes1.setLayout(jPanelOpcoes1Layout);
        jPanelOpcoes1Layout.setHorizontalGroup(
            jPanelOpcoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelOpcoes1Layout.setVerticalGroup(
            jPanelOpcoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable_Estoque_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Código", "Quantidade em estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Estoque_tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTable_Estoque_tabela);

        javax.swing.GroupLayout jPanelListaItens1Layout = new javax.swing.GroupLayout(jPanelListaItens1);
        jPanelListaItens1.setLayout(jPanelListaItens1Layout);
        jPanelListaItens1Layout.setHorizontalGroup(
            jPanelListaItens1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItens1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
        );
        jPanelListaItens1Layout.setVerticalGroup(
            jPanelListaItens1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItens1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton_Estoque_editar.setText("Editar");
        jButton_Estoque_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Estoque_editarActionPerformed(evt);
            }
        });

        jButton_Estoque_apagar.setText("Apagar");
        jButton_Estoque_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Estoque_apagarActionPerformed(evt);
            }
        });

        jButton_Estoque_novoItem.setText("Novo Item no estoque");
        jButton_Estoque_novoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Estoque_novoItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Estoque_novoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Estoque_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Estoque_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Estoque_novoItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Estoque_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Estoque_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEstoqueLayout = new javax.swing.GroupLayout(jPanelEstoque);
        jPanelEstoque.setLayout(jPanelEstoqueLayout);
        jPanelEstoqueLayout.setHorizontalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addComponent(jPanelOpcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListaItens1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEstoqueLayout.setVerticalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                        .addComponent(jPanelListaItens1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );

        jPanelContent.add(jPanelEstoque);

        jPanelVenda.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBackground(new java.awt.Color(71, 120, 197));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jTextField_Vendas_data.setBackground(new java.awt.Color(123, 156, 225));
        jTextField_Vendas_data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Vendas_data.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mês:");

        jButton_Venda_buscar_mes.setBackground(new java.awt.Color(71, 120, 197));
        jButton_Venda_buscar_mes.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Venda_buscar_mes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8_Search_18px.png"))); // NOI18N
        jButton_Venda_buscar_mes.setText("Buscar");
        jButton_Venda_buscar_mes.setBorder(null);
        jButton_Venda_buscar_mes.setBorderPainted(false);
        jButton_Venda_buscar_mes.setFocusable(false);
        jButton_Venda_buscar_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Venda_buscar_mesActionPerformed(evt);
            }
        });

        jButton_Vendas_buscarData.setBackground(new java.awt.Color(71, 120, 197));
        jButton_Vendas_buscarData.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Vendas_buscarData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8_Search_18px.png"))); // NOI18N
        jButton_Vendas_buscarData.setText("Buscar");
        jButton_Vendas_buscarData.setBorder(null);
        jButton_Vendas_buscarData.setBorderPainted(false);
        jButton_Vendas_buscarData.setFocusable(false);
        jButton_Vendas_buscarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Vendas_buscarDataActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Vendas");

        jComboBox_Vendas_meses.setMaximumRowCount(15);
        jComboBox_Vendas_meses.setBorder(null);
        jComboBox_Vendas_meses.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_Vendas_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Vendas_meses, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Venda_buscar_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Vendas_data, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Vendas_buscarData, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Vendas_buscarData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Vendas_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(jButton_Venda_buscar_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Vendas_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Vendas_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton_Vendas_totalItensVendidos.setText("Ver total de vendas por item");
        jButton_Vendas_totalItensVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Vendas_totalItensVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoes2Layout = new javax.swing.GroupLayout(jPanelOpcoes2);
        jPanelOpcoes2.setLayout(jPanelOpcoes2Layout);
        jPanelOpcoes2Layout.setHorizontalGroup(
            jPanelOpcoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Vendas_totalItensVendidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOpcoes2Layout.setVerticalGroup(
            jPanelOpcoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoes2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton_Vendas_totalItensVendidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Vendas_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Total Pago", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Vendas_tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(jTable_Vendas_tabela);

        jTextField_Vendas_total.setEditable(false);
        jTextField_Vendas_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Vendas_totalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setText("Total:");

        javax.swing.GroupLayout jPanelListaItens2Layout = new javax.swing.GroupLayout(jPanelListaItens2);
        jPanelListaItens2.setLayout(jPanelListaItens2Layout);
        jPanelListaItens2Layout.setHorizontalGroup(
            jPanelListaItens2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItens2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaItens2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelListaItens2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField_Vendas_total, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanelListaItens2Layout.setVerticalGroup(
            jPanelListaItens2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaItens2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaItens2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaItens2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(jTextField_Vendas_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jButton_Vendas_NovaVenda.setText("Nova Venda");
        jButton_Vendas_NovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Vendas_NovaVendaActionPerformed(evt);
            }
        });

        jButton_Vendas_Detalhe.setText("Ver detalhe da venda");
        jButton_Vendas_Detalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Vendas_DetalheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Vendas_Detalhe, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Vendas_NovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Vendas_NovaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Vendas_Detalhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Vendas_vendasDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Vendas_vendasDe.setText("Vendas de: ");

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addComponent(jPanelOpcoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelListaItens2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_Vendas_vendasDe, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel_Vendas_vendasDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelListaItens2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelContent.add(jPanelVenda);

        jPanelDespesa.setBackground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mês:");

        jButton_Despesas_buscar_mesAno.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Despesas_buscar_mesAno.setText("Buscar");
        jButton_Despesas_buscar_mesAno.setBorder(null);
        jButton_Despesas_buscar_mesAno.setBorderPainted(false);
        jButton_Despesas_buscar_mesAno.setFocusable(false);
        jButton_Despesas_buscar_mesAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Despesas_buscar_mesAnoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Despesas");

        jComboBox_Despesas_meses.setMaximumRowCount(15);
        jComboBox_Despesas_meses.setBorder(null);
        jComboBox_Despesas_meses.setFocusable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jComboBox_Despesas_anos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Despesas_meses, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Despesas_buscar_mesAno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(121, 121, 121))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jButton_Despesas_buscar_mesAno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Despesas_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Despesas_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton_Despesas_totalDespesasPorItem.setText(" Total de despesas por item");
        jButton_Despesas_totalDespesasPorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Despesas_totalDespesasPorItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoes3Layout = new javax.swing.GroupLayout(jPanelOpcoes3);
        jPanelOpcoes3.setLayout(jPanelOpcoes3Layout);
        jPanelOpcoes3Layout.setHorizontalGroup(
            jPanelOpcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoes3Layout.createSequentialGroup()
                .addComponent(jButton_Despesas_totalDespesasPorItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOpcoes3Layout.setVerticalGroup(
            jPanelOpcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoes3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton_Despesas_totalDespesasPorItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Despesas_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Item", "Categoria", "Valor gasto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Despesas_tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTable_Despesas_tabela);

        jTextField_Despesas_total.setEditable(false);
        jTextField_Despesas_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Despesas_totalActionPerformed(evt);
            }
        });

        jLabel_Despesas_totalDe.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_Despesas_totalDe.setText("Total:");

        javax.swing.GroupLayout jPanelListaItens3Layout = new javax.swing.GroupLayout(jPanelListaItens3);
        jPanelListaItens3.setLayout(jPanelListaItens3Layout);
        jPanelListaItens3Layout.setHorizontalGroup(
            jPanelListaItens3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaItens3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaItens3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(jPanelListaItens3Layout.createSequentialGroup()
                        .addComponent(jLabel_Despesas_totalDe)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField_Despesas_total, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelListaItens3Layout.setVerticalGroup(
            jPanelListaItens3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaItens3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaItens3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaItens3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_Despesas_totalDe))
                    .addComponent(jTextField_Despesas_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jButton_Despesas_novaDespesa.setText("Nova despesa");
        jButton_Despesas_novaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Despesas_novaDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(jButton_Despesas_novaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Despesas_novaDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Despesas_despesasDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Despesas_despesasDe.setText("Despesas de 2021-11: ");

        javax.swing.GroupLayout jPanelDespesaLayout = new javax.swing.GroupLayout(jPanelDespesa);
        jPanelDespesa.setLayout(jPanelDespesaLayout);
        jPanelDespesaLayout.setHorizontalGroup(
            jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDespesaLayout.createSequentialGroup()
                .addComponent(jPanelOpcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelListaItens3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Despesas_despesasDe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanelDespesaLayout.setVerticalGroup(
            jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDespesaLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDespesaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel_Despesas_despesasDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelListaItens3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelContent.add(jPanelDespesa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 890, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
        // TODO add your handling code here:
        visisbleFalse();
        jPanelVenda.setVisible(true);
        this.vendasController.setarTabela();
    }//GEN-LAST:event_jButtonVendasActionPerformed

    private void jButtonDesoesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesoesasActionPerformed
        // TODO add your handling code here:
        visisbleFalse();
        jPanelDespesa.setVisible(true);
        
        try {
            this.despesasController.setarTela();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDesoesasActionPerformed

    private void jButtonItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItensActionPerformed
        visisbleFalse();
        jPanelItem.setVisible(true);
        try {
            itensCotroller.preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButtonItensActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
       
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton_Itens_NovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Itens_NovoItemActionPerformed
        // TODO add your handling code here:
        NovoItem n= null;;
        try {
            n = new NovoItem();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButton_Itens_NovoItemActionPerformed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jButton_Estoque_novoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Estoque_novoItemActionPerformed
        // TODO add your handling code here:
        NovoItemEstoque n = new NovoItemEstoque();
        try {
            NovoItemEstoqueController.setarTela();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setVisible(true);
    }//GEN-LAST:event_jButton_Estoque_novoItemActionPerformed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jButton_Vendas_NovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Vendas_NovaVendaActionPerformed
        // TODO add your handling code here:
        NovoVenda nv= null;;
        try {
            nv = new NovoVenda();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        nv.setVisible(true);
    }//GEN-LAST:event_jButton_Vendas_NovaVendaActionPerformed

    private void jButton_Vendas_DetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Vendas_DetalheActionPerformed
        // TODO add your handling code here:
        
        Venda v = this.vendasController.obterVendaSeleciona();
        DetalheVenda dv = new DetalheVenda();
        
        try {
            DetalheVendaController.setarTela(v);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dv.setVisible(true);
    }//GEN-LAST:event_jButton_Vendas_DetalheActionPerformed

    private void jButton_Vendas_totalItensVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Vendas_totalItensVendidosActionPerformed
        // TODO add your handling code here:
        TotalVendasPorItem item= null;;
        try {
            item = new TotalVendasPorItem();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        item.setVisible(true);
    }//GEN-LAST:event_jButton_Vendas_totalItensVendidosActionPerformed

    private void jButton_Venda_buscar_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Venda_buscar_mesActionPerformed
        try {
            // TODO add your handling code here:
            this.vendasController.buscarMesEANo();
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Venda_buscar_mesActionPerformed

    private void jButton_Itens_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Itens_BuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.itensCotroller.buscar();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Itens_BuscarActionPerformed

    private void jButton_Itens_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Itens_EditarActionPerformed
        // TODO add your handling code here:
        Item i = new Item();
        i = this.itensCotroller.itemSelecionado();

        EditarItem editarItem = new EditarItem();
        try {
            editarItem.controller.preencherTela(i);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        editarItem.setVisible(true);
        
    }//GEN-LAST:event_jButton_Itens_EditarActionPerformed

    private void jButton_Estoque_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Estoque_buscarActionPerformed
        try {
            // TODO add your handling code here:
            this.estoqueController.buscar();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Estoque_buscarActionPerformed

    private void jButton_Estoque_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Estoque_editarActionPerformed
        // TODO add your handling code here:
        Estoque e = this.estoqueController.itemSelecionado();
        if(e == null) return;
        
        NovoItemEstoque n = new NovoItemEstoque();
        NovoItemEstoqueController.setarTelaEditar(e);
        n.setVisible(true);  
    }//GEN-LAST:event_jButton_Estoque_editarActionPerformed

    private void jButton_Estoque_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Estoque_apagarActionPerformed
        // TODO add your handling code here:
        Estoque e = this.estoqueController.itemSelecionado();
        if(e == null) return;
        try {
            this.estoqueController.apagar(e);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Estoque_apagarActionPerformed

    private void jButton_Vendas_buscarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Vendas_buscarDataActionPerformed

        try {
            // TODO add your handling code here:
            this.vendasController.buscarData();
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_Vendas_buscarDataActionPerformed

    private void jTextField_Vendas_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Vendas_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Vendas_totalActionPerformed

    private void jButton_Despesas_buscar_mesAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Despesas_buscar_mesAnoActionPerformed
        try {
            // TODO add your handling code here:
            this.despesasController.buscar();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Despesas_buscar_mesAnoActionPerformed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void jButton_Despesas_totalDespesasPorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Despesas_totalDespesasPorItemActionPerformed
        // TODO add your handling code here:
        TotalDespesasPorItem tdpi= null;;
        try {
            tdpi = new TotalDespesasPorItem();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tdpi.setVisible(true);
    }//GEN-LAST:event_jButton_Despesas_totalDespesasPorItemActionPerformed

    private void jTextField_Despesas_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Despesas_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Despesas_totalActionPerformed

    private void jButton_Despesas_novaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Despesas_novaDespesaActionPerformed
        // TODO add your handling code here:
        NovaDespesa nv = null;
        try {
            nv = new NovaDespesa();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        nv.setVisible(true);
    }//GEN-LAST:event_jButton_Despesas_novaDespesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
       
        
         //JOptionPane.showMessageDialog(rootPane, "Seçim yapınız.");
        
    }

    public JButton getjButton_Itens_Apagar() {
        return jButton_Itens_Apagar;
    }

    public void setjButton_Itens_Apagar(JButton jButton_Itens_Apagar) {
        this.jButton_Itens_Apagar = jButton_Itens_Apagar;
    }

    public JButton getjButton_Itens_Buscar() {
        return jButton_Itens_Buscar;
    }

    public void setjButton_Itens_Buscar(JButton jButton_Itens_Buscar) {
        this.jButton_Itens_Buscar = jButton_Itens_Buscar;
    }

    public JButton getjButton_Itens_Editar() {
        return jButton_Itens_Editar;
    }

    public void setjButton_Itens_Editar(JButton jButton_Itens_Editar) {
        this.jButton_Itens_Editar = jButton_Itens_Editar;
    }

    public JButton getjButton_Itens_NovoItem() {
        return jButton_Itens_NovoItem;
    }

    public void setjButton_Itens_NovoItem(JButton jButton_Itens_NovoItem) {
        this.jButton_Itens_NovoItem = jButton_Itens_NovoItem;
    }

    public JButton getjButton_NovoItemNoEstoque() {
        return jButton_Estoque_novoItem;
    }

    public void setjButton_NovoItemNoEstoque(JButton jButton_NovoItemNoEstoque) {
        this.jButton_Estoque_novoItem = jButton_NovoItemNoEstoque;
    }

    public JTable getjTable_Itens_TabelaItens() {
        return jTable_Itens_TabelaItens;
    }

    public void setjTable_Itens_TabelaItens(JTable jTable_Itens_TabelaItens) {
        this.jTable_Itens_TabelaItens = jTable_Itens_TabelaItens;
    }

    public JTextField getjTextField_Itens_Codigo() {
        return jTextField_Itens_Codigo;
    }

    public void setjTextField_Itens_Codigo(JTextField jTextField_Itens_Codigo) {
        this.jTextField_Itens_Codigo = jTextField_Itens_Codigo;
    }

    public JTextField getjTextField_Itens_Descricao() {
        return jTextField_Itens_Descricao;
    }

    public void setjTextField_Itens_Descricao(JTextField jTextField_Itens_Descricao) {
        this.jTextField_Itens_Descricao = jTextField_Itens_Descricao;
    }
    
    //////////////

    public JTable getjTable_Estoque_tabela() {
        return jTable_Estoque_tabela;
    }

    public void setjTable_Estoque_tabela(JTable jTable_Estoque_tabela) {
        this.jTable_Estoque_tabela = jTable_Estoque_tabela;
    }

    public JTextField getjTextField_Estoque_codigp() {
        return jTextField_Estoque_codigp;
    }

    public void setjTextField_Estoque_codigp(JTextField jTextField_Estoque_codigp) {
        this.jTextField_Estoque_codigp = jTextField_Estoque_codigp;
    }

    public JTextField getjTextField_Estoque_descricao() {
        return jTextField_Estoque_descricao;
    }

    public void setjTextField_Estoque_descricao(JTextField jTextField_Estoque_descricao) {
        this.jTextField_Estoque_descricao = jTextField_Estoque_descricao;
    }

    public JComboBox getjComboBox_Vendas_meses() {
        return jComboBox_Vendas_meses;
    }

    public void setjComboBox_Vendas_meses(JComboBox jComboBox_Vendas_meses) {
        this.jComboBox_Vendas_meses = jComboBox_Vendas_meses;
    }

    public JTextField getjTextField_Vendas_total() {
        return jTextField_Vendas_total;
    }

    public void setjTextField_Vendas_total(JTextField jTextField_Vendas_total) {
        this.jTextField_Vendas_total = jTextField_Vendas_total;
    }


    public JTable getjTable_Vendas_tabela() {
        return jTable_Vendas_tabela;
    }

    public void setjTable_Vendas_tabela(JTable jTable_Vendas_tabela) {
        this.jTable_Vendas_tabela = jTable_Vendas_tabela;
    }

    public JTextField getjTextField_Vendas_data() {
        return jTextField_Vendas_data;
    }

    public void setjTextField_Vendas_data(JTextField jTextField_Vendas_data) {
        this.jTextField_Vendas_data = jTextField_Vendas_data;
    }
    
    public JLabel getjLabel_Vendas_vendasDe() {
        return jLabel_Vendas_vendasDe;
    }

    public void setjLabel_Vendas_vendasDe(JLabel jLabel_Vendas_vendasDe) {
        this.jLabel_Vendas_vendasDe = jLabel_Vendas_vendasDe;
    }

    public JComboBox getjComboBox_Vendas_ano() {
        return jComboBox_Vendas_ano;
    }

    public void setjComboBox_Vendas_ano(JComboBox jComboBox_Vendas_ano) {
        this.jComboBox_Vendas_ano = jComboBox_Vendas_ano;
    }
    
    ///////////////
    
    public JComboBox getjComboBox_Despesas_anos() {
        return jComboBox_Despesas_anos;
    }

    public void setjComboBox_Despesas_anos(JComboBox jComboBox_Despesas_anos) {
        this.jComboBox_Despesas_anos = jComboBox_Despesas_anos;
    }

    public JComboBox getjComboBox_Despesas_meses() {
        return jComboBox_Despesas_meses;
    }

    public void setjComboBox_Despesas_meses(JComboBox jComboBox_Despesas_meses) {
        this.jComboBox_Despesas_meses = jComboBox_Despesas_meses;
    }

    public JLabel getjLabel_Despesas_despesasDe() {
        return jLabel_Despesas_despesasDe;
    }

    public void setjLabel_Despesas_despesasDe(JLabel jLabel_Despesas_despesasDe) {
        this.jLabel_Despesas_despesasDe = jLabel_Despesas_despesasDe;
    }

    public JLabel getjLabel_Despesas_totalDe() {
        return jLabel_Despesas_totalDe;
    }

    public void setjLabel_Despesas_totalDe(JLabel jLabel_Despesas_totalDe) {
        this.jLabel_Despesas_totalDe = jLabel_Despesas_totalDe;
    }

    public JTable getjTable_Despesas_tabela() {
        return jTable_Despesas_tabela;
    }

    public void setjTable_Despesas_tabela(JTable jTable_Despesas_tabela) {
        this.jTable_Despesas_tabela = jTable_Despesas_tabela;
    }

    public JTextField getjTextField_Despesas_total() {
        return jTextField_Despesas_total;
    }

    public void setjTextField_Despesas_total(JTextField jTextField_Despesas_total) {
        this.jTextField_Despesas_total = jTextField_Despesas_total;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDesoesas;
    private javax.swing.JButton jButtonItens;
    private javax.swing.JButton jButtonVendas;
    private javax.swing.JButton jButton_Despesas_buscar_mesAno;
    private javax.swing.JButton jButton_Despesas_novaDespesa;
    private javax.swing.JButton jButton_Despesas_totalDespesasPorItem;
    private javax.swing.JButton jButton_Estoque_apagar;
    private javax.swing.JButton jButton_Estoque_buscar;
    private javax.swing.JButton jButton_Estoque_editar;
    private javax.swing.JButton jButton_Estoque_novoItem;
    private javax.swing.JButton jButton_Itens_Apagar;
    private javax.swing.JButton jButton_Itens_Buscar;
    private javax.swing.JButton jButton_Itens_Editar;
    private javax.swing.JButton jButton_Itens_NovoItem;
    private javax.swing.JButton jButton_Venda_buscar_mes;
    private javax.swing.JButton jButton_Vendas_Detalhe;
    private javax.swing.JButton jButton_Vendas_NovaVenda;
    private javax.swing.JButton jButton_Vendas_buscarData;
    private javax.swing.JButton jButton_Vendas_totalItensVendidos;
    private javax.swing.JComboBox jComboBox_Despesas_anos;
    private javax.swing.JComboBox jComboBox_Despesas_meses;
    private javax.swing.JComboBox jComboBox_Vendas_ano;
    private javax.swing.JComboBox jComboBox_Vendas_meses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Despesas_despesasDe;
    private javax.swing.JLabel jLabel_Despesas_totalDe;
    private javax.swing.JLabel jLabel_Vendas_vendasDe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelDespesa;
    private javax.swing.JPanel jPanelEstoque;
    private javax.swing.JPanel jPanelItem;
    private javax.swing.JPanel jPanelListaItens;
    private javax.swing.JPanel jPanelListaItens1;
    private javax.swing.JPanel jPanelListaItens2;
    private javax.swing.JPanel jPanelListaItens3;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JPanel jPanelOpcoes1;
    private javax.swing.JPanel jPanelOpcoes2;
    private javax.swing.JPanel jPanelOpcoes3;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable_Despesas_tabela;
    private javax.swing.JTable jTable_Estoque_tabela;
    private javax.swing.JTable jTable_Itens_TabelaItens;
    private javax.swing.JTable jTable_Vendas_tabela;
    private javax.swing.JTextField jTextField_Despesas_total;
    private javax.swing.JTextField jTextField_Estoque_codigp;
    private javax.swing.JTextField jTextField_Estoque_descricao;
    private javax.swing.JTextField jTextField_Itens_Codigo;
    private javax.swing.JTextField jTextField_Itens_Descricao;
    private javax.swing.JTextField jTextField_Vendas_data;
    private javax.swing.JTextField jTextField_Vendas_total;
    // End of variables declaration//GEN-END:variables
}
